---
# handlers file for install_docker

- name: restart_and_check_docker
  ansible.builtin.service:
    name: docker
    state: restarted
  notify: ensure_docker_active   
- name: ensure_docker_active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true